#
# Firefox Dev Channel
#

FROM ubuntu:14.04.2


MAINTAINER Justin Wilson <justin@minty.io>


RUN apt-get update && apt-get install -y \
	libfontconfig \
	libfreetype6 \
	libxrender1 \
	libasound2 \
	libdbus-glib-1-2 \
	libgtk2.0-0 \
	libxcomposite1 \
	libxdamage1 \
	libxext6 \
	libxfixes3 \
	libxt6


ADD https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=linux64&lang=en-US /tmp/firefox.tar.bz2

RUN mkdir /opt/firefox
RUN mkdir /data
RUN tar xjf /tmp/firefox.tar.bz2 -C /opt

ENTRYPOINT ["/opt/firefox/firefox"]
CMD ["-profile", "/data"]
